apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: h6t8ox7kx-nodejs 
  janus-idp.io/tekton: h6t8ox7kx-nodejs
  backstage.io/kubernetes-id: h6t8ox7kx-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h6t8ox7kx-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml